# Site settings
title: ⧉
title_separator: "|"
email: hello@justinpickard.net
description: Notes and log entries, for the time being.
url: "https://jcalpickard.github.io" # Update with your GitHub Pages URL
permalink: /log/:year/:month/:day/:title/
header_pages:
  - index.md
  - hello.md
  - log.md
  - phd.md

sass:
  sass_dir: _sass
  style: compressed # or :nested, :compact, :expanded

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache