# Site settings
title: ⧉
author: "Justin Pickard"
email: jcalpickard@proton.me
description: Notes and log entries, for now.
url: "https://jcalpickard.github.io" # Update with your GitHub Pages URL
permalink: /log/:year/:month/:day/:title/

header_pages:
  - hello.md
  - index.md
  - phd.md
  - log.md
  - compost/index.md

sass:
  sass_dir: _sass
  style: compressed # or :nested, :compact, :expanded

collections:
  compost:
    output: true
  compost_tags:
    permalink: compost/tags/:name/
    output: true

defaults:
  - scope:
      path: ''
      type: compost_tags
    values:
      permalink: "compost/tags/:name/"
      layout: tag

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Kramdown settings
kramdown:
  footnote_backlink: "⤴\uFE0E" # Use ⤴ symbol instead of ↩