port: 3000
lsi: false
permalink: /:title
markdown: kramdown
theme: null
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
exclude:
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - _config-dev.yml
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
redirect_from:
  json: false
