name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main  # Set this to your default branch

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE so that the workflow can access its contents
      with:
        fetch-depth: 0  # Important for some plugins and for jekyll-last-modified-at

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.1'  # Specify the Ruby version you are using, match it with your local development environment
        bundler-cache: true  # Automatically caches and installs gems

    - name: Build and test site # Installs dependencies and builds your site using Jekyll
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages # Deploys your _site directory to the gh-pages branch of your repository, from which GitHub Pages will serve your site
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
